include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=hpcdtoppm 

hpcdtoppm_C_FILES= color.c const.c error.c format.c hpcdtoppm.c output.c \
                   ppm.c tools.c


hpcdtoppm_HEADER_FILES= config.h hpcdtoppm.h


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
