include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=Noise
BUNDLE_NAME= Noise
BUNDLE_EXTENSION=.bundle

Noise_OBJC_FILES= NoiseCtr.m Noiser.m Mosaicker.m

Noise_HEADER_FILES= NoiseCtr.h Noiser.h Mosaicker.h

Noise_RESOURCE_FILES=Noise.gorm

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
