// _InfoPanel_macos_EOArchive_English.java
// Generated by EnterpriseObjects palette at Tuesday, July 19, 2005 12:49:46 PM Europe/Zurich

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _InfoPanel_macos_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0, _nsImageView1, _nsImageView2, _nsImageView3, _nsImageView4, _nsImageView5;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2;
    javax.swing.JButton _nsButton0, _nsButton1;
    javax.swing.JPanel _nsView0, _nsView1;

    public _InfoPanel_macos_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsImageView5 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsImageView4 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "Field1");
        _nsImageView3 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsImageView2 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "Field");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("http://www.sente.ch/software/cvl"), "");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("cvl-feedback@sente.ch"), "");
        _nsImageView1 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "2");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "cvsInfoPanel")) != null)) {
            _eoFrame1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame1");
        } else {
            _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "cvs");
        }

        _nsView1 = (JPanel)_eoFrame1.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textView")) != null)) {
            _nsTextView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView0");
        } else {
            _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "6");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "versionCell")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        }

        _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "thePanel")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "InfoPanel");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "openURL", _nsButton1), ""));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "openMailer", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _connect(_owner(), _eoFrame1, "cvsInfoPanel");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_owner(), _nsTextView0, "textView");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "thePanel");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "versionCell");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField6, "Helvetica", 18, Font.PLAIN + Font.BOLD);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Concurrent Versions Librarian");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _setFontForComponent(_nsTextField5, "Helvetica", 10, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("http://www.sente.ch/software/cvl/");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField5.setSelectable(true);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        _setFontForComponent(_nsTextField4, "Helvetica", 10, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("cvl-feedback@sente.ch");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField4.setSelectable(true);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsTextField4.setSize(159, 13);
        _nsTextField4.setLocation(40, 4);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsTextField4);
        _nsTextField5.setSize(159, 13);
        _nsTextField5.setLocation(40, 19);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsTextField5);
        _nsImageView4.setSize(30, 15);
        _nsImageView4.setLocation(13, 0);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsImageView4, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsImageView4);
        _nsImageView5.setSize(30, 18);
        _nsImageView5.setLocation(13, 16);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsImageView5, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsImageView5);
        _nsButton0.setSize(26, 12);
        _nsButton0.setLocation(13, 5);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsButton0);
        _nsButton1.setSize(26, 12);
        _nsButton1.setLocation(13, 20);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsButton1);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(393, 1);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField3, "Helvetica", 10, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("Swiss Made");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Helvetica", 10, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Copyright 1997-2005, Sente SA. All rights reserved.");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsButton1, "Lucida Grande", 14, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton0, "Lucida Grande", 14, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField1, "Lucida Grande", 24, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("About cvs...");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsTextField1.setSize(380, 30);
        _nsTextField1.setLocation(69, 7);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField1);
        _nsImageView1.setSize(48, 48);
        _nsImageView1.setLocation(5, 6);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsImageView1, EOViewLayout.MinYMargin);
        _nsView1.add(_nsImageView1);
        _nsTextView0.setSize(448, 182);
        _nsTextView0.setLocation(5, 65);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextView0);

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _nsView1.setSize(462, 248);
            _eoFrame1.setTitle("");
            _eoFrame1.setLocation(384, 418);
            _eoFrame1.setSize(462, 248);
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _nsTextView0.setEditable(false);
            _nsTextView0.setOpaque(true);
            _nsTextView0.setText("Retrieving information...");
            _setFontForComponent(_nsTextView0.textArea(), "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Helvetica", 10, Font.PLAIN);
            _nsTextField0.setEditable(false);
            _nsTextField0.setOpaque(false);
            _nsTextField0.setText("version beta1");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
            _nsTextField0.setBorder(null);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsImageView0.setSize(397, 445);
        _nsImageView0.setLocation(-39, -17);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsImageView0);
        _nsTextField0.setSize(312, 14);
        _nsTextField0.setLocation(-4, 299);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField2.setSize(257, 13);
        _nsTextField2.setLocation(-4, 317);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsImageView2.setSize(277, 144);
        _nsImageView2.setLocation(10, 3);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsImageView2);
        _nsImageView3.setSize(66, 55);
        _nsImageView3.setLocation(139, 156);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsImageView3);
        _nsTextField3.setSize(63, 13);
        _nsTextField3.setLocation(284, 317);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _nsBox0.setSize(397, 5);
        _nsBox0.setLocation(-15, 313);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsBox2.setSize(211, 31);
        _nsBox2.setLocation(64, 262);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox2);
        _nsTextField6.setSize(277, 23);
        _nsTextField6.setLocation(32, 210);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField6);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(339, 344);
            _eoFrame0.setTitle("");
            _eoFrame0.setLocation(183, 354);
            _eoFrame0.setSize(339, 344);
        }
    }
}
