include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=pcx2pxo 

pcx2pxo_C_FILES= pcx2pxo.c imfunc.c pcxbmap.c pcxheader.c

pcx2pxo_HEADER_FILES= pxc.h

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
