include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=ImageOpr
BUNDLE_NAME= ImageOpr
BUNDLE_EXTENSION=.bundle

ImageOpr_OBJC_FILES=CmykConverter.m ImageMono.m ImageOpr.m MonoCtr.m \
		     MonotoneView.m ReduceCtr.m RotateCtr.m rotate.m RotateView.m \
		      SmResizeCtr.m

ImageOpr_HEADER_FILES=CmykConverter.h ImageOpr.h MonoCtr.h MonotoneView.h \
		       ReduceCtr.h RotateCtr.h rotate.h RotateView.h SmResizeCtr.h 


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble

