include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=Enhance
BUNDLE_NAME= Enhance
BUNDLE_EXTENSION=.bundle

Enhance_OBJC_FILES= EnhanceCtr.m Enhancer.m Embosser.m ContourCtr.m Contourer.m Blurrer.m

Enhance_HEADER_FILES= EnhanceCtr.h Enhancer.h Embosser.h ContourCtr.h Contourer.h Blurrer.h

Enhance_RESOURCE_FILES=Enhance.gorm

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
