include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=mag2pxo 

mag2pxo_C_FILES= mag2pxo.c sjis2euc.c magbmap.c magheader.c

mag2pxo_HEADER_FILES= mag.h  sjis2euc.h

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
