include $(GNUSTEP_MAKEFILES)/common.make

VERSION = 1.0BETA
PACKAGE_NAME = PikoPixel
APP_NAME = PikoPixel

PikoPixel_APPLICATION_ICON = GNUstepAppIcon.png

PikoPixel_OBJC_PRECOMPILED_HEADERS = PikoPixel_Prefix.pch

PikoPixel_OBJC_FILES = \
    main.m \
     \
    PPApplication.m \
     \
    PPDocument.m \
    PPDocument_ActiveTool.m \
    PPDocument_CanvasSettings.m \
    PPDocument_Drawing.m \
    PPDocument_FileFormats.m \
    PPDocument_LayerOperationTarget.m \
    PPDocument_Layers.m \
    PPDocument_MirroringRotating.m \
    PPDocument_Moving.m \
    PPDocument_NativeFileFormat.m \
    PPDocument_NativeFileIcon.m \
    PPDocument_NotificationOverrides.m \
    PPDocument_Notifications.m \
    PPDocument_Pasteboard.m \
    PPDocument_PixelMatching.m \
    PPDocument_Resizing.m \
    PPDocument_SamplerImages.m \
    PPDocument_Saving.m \
    PPDocument_Selection.m \
    PPDocument_Tiling.m \
    PPDocumentLayer.m \
    PPDocumentSamplerImage.m \
     \
    PPToolbox.m \
    PPTool.m \
    PPToolUtilities.m \
    PPPencilTool.m \
    PPEraserTool.m \
    PPFillTool.m \
    PPLineTool.m \
    PPRectTool.m \
    PPOvalTool.m \
    PPFreehandSelectTool.m \
    PPRectSelectTool.m \
    PPMagicWandTool.m \
    PPColorSamplerTool.m \
    PPMoveTool.m \
    PPMagnifierTool.m \
    PPColorRampTool.m \
     \
    PPDocumentWindowController.m \
    PPDocumentWindowController_Actions.m \
    PPDocumentWindowController_MenuValidation.m \
    PPDocumentWindowController_Notifications.m \
    PPDocumentWindowController_Sheets.m \
    PPDocumentWindow.m \
     \
    PPCanvasView.m \
    PPCanvasView_Autoscrolling.m \
    PPCanvasView_ColorRampToolOverlay.m \
    PPCanvasView_EraserToolOverlay.m \
    PPCanvasView_FillToolOverlay.m \
    PPCanvasView_MagnifierToolOverlay.m \
    PPCanvasView_MatchToolToleranceIndicator.m \
    PPCanvasView_MouseCursor.m \
    PPCanvasView_Notifications.m \
    PPCanvasView_SelectionOutline.m \
    PPCanvasView_SelectionToolOverlay.m \
     \
    PPDocumentSheetController.m \
    PPDocumentAnimationFileNoticeSheetController.m \
    PPDocumentBackgroundSettingsSheetController.m \
    PPDocumentEditImageSizePresetsSheetController.m \
    PPDocumentEditPatternPresetsSheetController.m \
    PPPresettablePatternView.m \
    PPDocumentFlattenedSaveNoticeSheetController.m \
    PPDocumentGridSettingsSheetController.m \
    PPDocumentResizeSheetController.m \
    PPDocumentSamplerImagesSettingsSheetController.m \
    PPDocumentScaleSheetController.m \
    PPScaledImageView.m \
    PPDocumentSizeSheetController.m \
    PPExportPanelAccessoryViewController.m \
     \
    PPPanelsController.m \
    PPPanelController.m \
    PPToolsPanelController.m \
    PPLayersPanelController.m \
    PPLayersTableView.m \
    PPLayerEnabledButtonCell.m \
    PPLayerOpacitySliderCell.m \
    PPLayerBlendingModeButton.m \
    PPPreviewPanelController.m \
    PPPreviewView.m \
    PPSamplerImagePanelController.m \
    PPToolModifierTipsPanelController.m \
    PPToolModifierTipsText.m \
     \
    PPPopupPanelsController.m \
    PPPopupPanelController.m \
    PPPopupPanel.m \
    PPFilledRoundedRectView.m \
    PPNavigatorPopupPanelController.m \
    PPNavigatorPopupView.m \
    PPToolsPopupPanelController.m \
    PPColorPickerPopupPanelController.m \
    PPColorPickerPopupPanel.m \
    PPSamplerImagePopupPanelController.m \
    PPResizeControl.m \
    PPLayerControlsPopupPanelController.m \
    PPScreencastPopupPanelController.m \
     \
    PPLayerControlButtonImagesManager.m \
    PPLayerControlButtonImagesManager_Notifications.m \
    PPCompositeThumbnail.m \
    PPMiniColorWell.m \
    PPSamplerImageView.m \
    PPToolButtonMatrix.m \
     \
    PPHotkeySettingsWindowController.m \
     \
    PPCursorManager.m \
     \
    PPThumbnailImageView.m \
    PPColorWell.m \
    PPKeyCancellableWindow.m \
    PPTitleablePopUpButton.m \
    PPParabolicSlider.m \
     \
    PPBackgroundPattern.m \
    PPGridPattern.m \
    PPHotkeys.m \
    PPImageSizePresets.m \
    PPPatternPresets.m \
    PPBackgroundPatternPresets.m \
    PPGridPatternPresets.m \
    PPUserDefaults.m \
     \
    NSBezierPath_PPUtilities.m \
    NSBezierPath_PPUtilities_MaskBitmapPaths.m \
    NSBitmapImageRep_PPUtilities.m \
    NSBitmapImageRep_PPUtilities_ColorMasking.m \
    NSBitmapImageRep_PPUtilities_ImageBitmaps.m \
    NSBitmapImageRep_PPUtilities_LinearRGB16Bitmaps.m \
    NSBitmapImageRep_PPUtilities_MaskBitmaps.m \
    NSBitmapImageRep_PPUtilities_PatternBitmaps.m \
    NSColor_PPUtilities.m \
    NSColor_PPUtilities_PatternColors.m \
    NSColorPanel_PPUtilities.m \
    NSCursor_PPUtilities.m \
    NSDocument_PPUtilities.m \
    NSDocumentController_PPUtilities.m \
    NSError_PPUtilities.m \
    NSEvent_PPUtilities.m \
    NSFileManager_PPUtilities.m \
    NSImage_PPUtilities.m \
    NSImageRep_PPUtilities.m \
    NSMutableArray_PPUtilities.m \
    NSObject_PPUtilities.m \
    NSObject_PPUtilities_MethodSwizzling.m \
    NSPasteboard_PPUtilities.m \
    NSTextField_PPUtilities.m \
    NSWindow_PPUtilities.m \
    NSData_PPNativePasteboardType.m \
     \
    PPAppBootUtilities.m \
    PPGeometry.m \
    PPHotkeyDisplayUtilities.m \
    PPImagePixelAlphaPremultiplyTables.m \
    PPKeyboardLayout.m \
    PPObjCUtilities.m \
    PPSRGBUtilities.m \
    PPTextAttributesDicts.m \
    PPUserFolderPaths.m \
     \
    PPGNUstepGlue_BezierPathAliasing.m \
    PPGNUstepGlue_BitmapGraphicsContext.m \
    PPGNUstepGlue_BitmapNonpremultipliedPNG.m \
    PPGNUstepGlue_ColorPanel.m \
    PPGNUstepGlue_ColorPickerPopupPanel.m \
    PPGNUstepGlue_CustomTheme.m \
    PPGNUstepGlue_DisableMenuKeysDuringTextEntry.m \
    PPGNUstepGlue_DocumentAutosaving.m \
    PPGNUstepGlue_DocumentSheets.m \
    PPGNUstepGlue_DocumentWindow.m \
    PPGNUstepGlue_ImageRecacheSpeedups.m \
    PPGNUstepGlue_KeyCancellableWindow.m \
    PPGNUstepGlue_KeyUpEvents.m \
    PPGNUstepGlue_LayerControlsPopupMenu.m \
    PPGNUstepGlue_LayersTable.m \
    PPGNUstepGlue_MenuKeyEquivalents.m \
    PPGNUstepGlue_MenuUpdates.m \
    PPGNUstepGlue_MenuView.m \
    PPGNUstepGlue_MenuWindowHiding.m \
    PPGNUstepGlue_Miscellaneous.m \
    PPGNUstepGlue_ModalSessions.m \
    PPGNUstepGlue_ModalSheets.m \
    PPGNUstepGlue_ModifierKeys.m \
    PPGNUstepGlue_PanelResizing.m \
    PPGNUstepGlue_PatternColorDrawingSpeedup.m \
    PPGNUstepGlue_PatternedLines.m \
    PPGNUstepGlue_PopupPanelFrames.m \
    PPGNUstepGlue_PopupPanelHidingOnWindowMove.m \
    PPGNUstepGlue_PreviewImageViewResizing.m \
    PPGNUstepGlue_ResizeControl.m \
    PPGNUstepGlue_ScrollerAutohiding.m \
    PPGNUstepGlue_SegmentedCellTracking.m \
    PPGNUstepGlue_SliderDragging.m \
    PPGNUstepGlue_TIFFRepresentations.m \
    PPGNUstepGlue_TitleablePopUpButton.m \
    PPGNUstepGlue_ViewDisplayCaching.m \
    PPGNUstepGlue_WindowOrdering.m \
    PPGNUstepGlue_WindowStyleOffsets.m \
    PPGNUstepGlue_Workspace.m \
    PPGNUstepGlueUtilities.m \
     \
    PPOptional_CanvasSpeedCheck.m \
    PPOptional_Screencasting.m \
    PPScreencastController.m

PikoPixel_RESOURCE_FILES = \
    images/GNUstepAppIcon.png \
    com.twilightedge.PikoPixel.appdata.xml \
     \
    images/arrow_left_button.png \
    images/arrow_outline_left_button.png \
    images/arrow_outline_right_button.png \
    images/arrow_right_button.png \
    images/blend_mode_icon_linear.png \
    images/blend_mode_icon_standard.png \
    images/checkerboard_segment.png \
    images/diagonal_checkerboard_segment.png \
    images/diagonal_lines_segment.png \
    images/eraser_tool_overlay_outline_pattern.png \
    images/gridpatternpreview_foreground.png \
    images/gridtype_crosshairs_segment.png \
    images/gridtype_dots_segment.png \
    images/gridtype_largedots_segment.png \
    images/gridtype_lines_segment.png \
    images/isometric_checkerboard_segment.png \
    images/isometric_lines_segment.png \
    images/marching_ants_pattern.png \
    images/minus_button_overlay.png \
    images/minus_button_overlay_small.png \
    images/neko.png \
    images/pencil_segment.png \
    images/plus_button_overlay.png \
    images/plus_button_overlay_small.png \
    images/resize_control.png \
    images/selection_tool_overlay_add_pattern.png \
    images/selection_tool_overlay_subtract_pattern.png \
    images/solid_segment.png \
    images/target_draw_layer_icon.png \
    images/target_enabled_layers_icon.png \
    images/view_draw_layer_icon.png \
    images/view_enabled_layers_icon.png \
     \
    images/tools/color_ramp_cursor.png \
    images/tools/eraser_button.png \
    images/tools/eraser_cursor.png \
    images/tools/eyedropper_button.png \
    images/tools/eyedropper_cursor.png \
    images/tools/freehand_select_button.png \
    images/tools/freehand_select_cursor.png \
    images/tools/line_button.png \
    images/tools/line_cursor.png \
    images/tools/magnifier_button.png \
    images/tools/magnifier_cursor.png \
    images/tools/move_button.png \
    images/tools/move_cursor.png \
    images/tools/move_selection_outline_cursor.png \
    images/tools/oval_button.png \
    images/tools/oval_cursor.png \
    images/tools/paintcan_button.png \
    images/tools/paintcan_cursor.png \
    images/tools/pencil_button.png \
    images/tools/pencil_cursor.png \
    images/tools/rect_button.png \
    images/tools/rect_cursor.png \
    images/tools/selection_rect_button.png \
    images/tools/selection_rect_cursor.png \
    images/tools/wand_button.png \
    images/tools/wand_cursor.png \
     \
    hotkey_defaults/Hotkeys_ar.plist \
    hotkey_defaults/Hotkeys_be.plist \
    hotkey_defaults/Hotkeys_bg.plist \
    hotkey_defaults/Hotkeys_cs.plist \
    hotkey_defaults/Hotkeys_da.plist \
    hotkey_defaults/Hotkeys_de_AT.plist \
    hotkey_defaults/Hotkeys_de_CH.plist \
    hotkey_defaults/Hotkeys_de.plist \
    hotkey_defaults/Hotkeys_el.plist \
    hotkey_defaults/Hotkeys_en_AU.plist \
    hotkey_defaults/Hotkeys_en_CA.plist \
    hotkey_defaults/Hotkeys_en_GB.plist \
    hotkey_defaults/Hotkeys_en.plist \
    hotkey_defaults/Hotkeys_en_US.plist \
    hotkey_defaults/Hotkeys_es.plist \
    hotkey_defaults/Hotkeys_et.plist \
    hotkey_defaults/Hotkeys_fa.plist \
    hotkey_defaults/Hotkeys_fi.plist \
    hotkey_defaults/Hotkeys_fr_CA.plist \
    hotkey_defaults/Hotkeys_fr_CH.plist \
    hotkey_defaults/Hotkeys_fr.plist \
    hotkey_defaults/Hotkeys_he.plist \
    hotkey_defaults/Hotkeys_hr.plist \
    hotkey_defaults/Hotkeys_hu.plist \
    hotkey_defaults/Hotkeys_hy.plist \
    hotkey_defaults/Hotkeys_is.plist \
    hotkey_defaults/Hotkeys_it.plist \
    hotkey_defaults/Hotkeys_lt.plist \
    hotkey_defaults/Hotkeys_lv.plist \
    hotkey_defaults/Hotkeys_mi.plist \
    hotkey_defaults/Hotkeys_mk.plist \
    hotkey_defaults/Hotkeys_mt.plist \
    hotkey_defaults/Hotkeys_nb.plist \
    hotkey_defaults/Hotkeys_ne.plist \
    hotkey_defaults/Hotkeys_nl_BE.plist \
    hotkey_defaults/Hotkeys_nl.plist \
    hotkey_defaults/Hotkeys_pl.plist \
    hotkey_defaults/Hotkeys_ps.plist \
    hotkey_defaults/Hotkeys_pt_BR.plist \
    hotkey_defaults/Hotkeys_pt_PT.plist \
    hotkey_defaults/Hotkeys_ro.plist \
    hotkey_defaults/Hotkeys_ru.plist \
    hotkey_defaults/Hotkeys_sk.plist \
    hotkey_defaults/Hotkeys_sl.plist \
    hotkey_defaults/Hotkeys_sr-Cyrl.plist \
    hotkey_defaults/Hotkeys_sv.plist \
    hotkey_defaults/Hotkeys_th.plist \
    hotkey_defaults/Hotkeys_tr.plist \
    hotkey_defaults/Hotkeys_uk.plist \
    hotkey_defaults/Hotkeys_uz.plist \
    hotkey_defaults/Hotkeys_vi.plist \
     \
    PPGNUstepDefaults_CustomTheme.plist

PikoPixel_LOCALIZED_RESOURCE_FILES = \
    MainMenu.nib \
     \
    InfoPlist.strings \
    KeyboardNameToLocale.plist \
    ToolModifierTipsStrings.plist \
     \
    ColorPickerPopupPanel.nib \
    DocumentBackgroundSettingsSheet.nib \
    DocumentEditPatternPresetsSheet.nib \
    DocumentEditSizePresetsSheet.nib \
    DocumentFlattenedSaveNoticeSheet.nib \
    DocumentGridSettingsSheet.nib \
    DocumentResizeSheet.nib \
    DocumentSamplerImagesSettingsSheet.nib \
    DocumentScaleSheet.nib \
    DocumentSizeSheet.nib \
    DocumentWindow.nib \
    ExportPanelAccessoryView.nib \
    HotkeySettings.nib \
    LayerControlButtonImageViews.nib \
    LayerControlsPopupPanel.nib \
    LayersPanel.nib \
    NavigatorPopupPanel.nib \
    PreviewPanel.nib \
    SamplerImagePanel.nib \
    SamplerImagePopupPanel.nib \
    ScreencastPopupPanel.nib \
    ToolModifierTipsPanel.nib \
    ToolsPanel.nib \
    ToolsPopupPanel.nib

PikoPixel_LANGUAGES = \
    English

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make

-include GNUmakefile.postamble

