include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=Dithering
FRAMEWORK_NAME=Dithering 
FRAMEWORK_EXTENSION=.framework

Dithering_OBJC_FILES=Dither.m FSmethod.m MDAmethod.m

Dithering_HEADER_FILES=Dither.h Dithering.h FSmethod.h MDAmethod.h

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/framework.make
-include GNUmakefile.postamble
