include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=png2pao 

png2pao_C_FILES= convert.c png2pao.c sub.c

png2pao_HEADER_FILES= png2pao.h png.h


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble



