include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=pxo2bmp 

pxo2bmp_C_FILES=bmpsave.c pxo2bmp.c pxoread.c

pxo2bmp_HEADER_FILES=bmp.h


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
