#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
view
directory RZBrowserCell.subproj
directory CoModulePanel.subproj
directory ImportPanel.subproj
directory Preferences.subproj
directory Inspector.subproj
directory MiscClockView.subproj
directory InfoPanel.subproj
