include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=ColorChange
BUNDLE_NAME= ColorChange
BUNDLE_EXTENSION=.bundle

ColorChange_OBJC_FILES= ColorChanger.m ColorChangeCtr.m

ColorChange_HEADER_FILES= ColorChanger.h ColorChangeCtr.h 

ColorChange_RESOURCE_FILES=ColorChange.gorm

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
