include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=Reduction
BUNDLE_NAME= Reduction
BUNDLE_EXTENSION=.bundle

Reduction_OBJC_FILES=FScolor.m ImageColorHalf.m ImageCutDown.m ImageReduce.m

Reduction_C_FILES=syspal.c

Reduction_HEADER_FILES=FScolor.h ImageReduce.h

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
