/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import <AppKit/AppKit.h>

int main(int argc, char *argv[]) {
  NSAutoreleasePool *pool;
  pool = [[NSAutoreleasePool alloc] init];
    [NSApplication sharedApplication];
    if ([NSBundle loadNibNamed:@"ToyViewer" owner:NSApp])
      [NSApp run];
    else 
      NSLog(@"miaou");

	    
    [NSApp release];
    return 0;
}
