include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=bmp2pxo 

bmp2pxo_C_FILES=bmp2pxo.c bmpheader.c bmpimage.c


bmp2pxo_HEADER_FILES=bmp.h


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble






