include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=SoftFrame
BUNDLE_NAME= SoftFrame
BUNDLE_EXTENSION=.bundle

SoftFrame_OBJC_FILES= SoftFrameCtr.m  SoftFramer.m SFAqua.m

SoftFrame_HEADER_FILES= SoftFrameCtr.h SoftFramer.h SFAqua.h

SoftFrame_RESOURCE_FILES=SoftFrame.gorm

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
