#
#	GNUmakefile
#
#       Compile the Pixen application
#


include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME=Pixen
#VERSION=
Pixen_APPLICATION_ICON=Pixen.tiff

Pixen_MAIN_MODEL_FILE = MainMenu

Pixen_OBJC_FILES = KTCuboidHash.m\
PXPattern.m\
KTMatrix.m\
KTMatrixDenseEnumerator.m\
KTMatrixDenseImp.m\
KTMatrixImp.m\
KTMatrixSparseEnumerator.m\
KTMatrixSparseImp.m\
KTMutableMatrix.m\
KTMutableMatrixDenseImp.m\
KTMutableMatrixImp.m\
KTMutableMatrixSparseImp.m\
KTPlaceholderMatrix.m\
KTPlaceholderMutableMatrix.m\
PXDocument.m\
NSArray_DeepMutableCopy.m\
PXAboutController.m\
PXAboutPanel.m\
PXAppDelegate.m\
PXBackground.m\
PXBackgroundController.m\
PXBicubicScaleAlgorithm.m\
PXCanvas.m\
PXCanvasController.m\
PXCanvasPrintView.m\
PXCanvasResizePrompter.m\
PXCanvasResizeView.m\
PXCanvasView.m\
PXCanvas_ApplescriptAdditions.m\
PXCheckeredBackground.m\
PXColorPaletteController.m\
PXColorPaletteMatrix.m\
PXColorWell.m\
PXColorWellCell.m\
PXCrosshair.m\
PXDuotoneBackground.m\
PXEllipseTool.m\
PXEllipseToolPropertiesView.m\
PXEmptyPropertiesView.m\
PXEraserTool.m\
PXEyedropperTool.m\
PXFillTool.m\
PXFilterController.m\
PXGradientBuilderController.m\
PXGrid.m\
PXGridSettingsPrompter.m\
PXHotkeyFormatter.m\
PXImage.m\
PXImageBackground.m\
PXImageSizePrompter.m\
PXImageView.m\
PXInfoPanelController.m\
PXLassoTool.m\
PXLayer.m\
PXLayerController.m\
PXLayerDetailsSubView.m\
PXLayerDetailsView.m\
PXLineTool.m\
PXLinearTool.m\
PXMagicWandTool.m\
PXMonotoneBackground.m\
PXMoveTool.m\
PXNamePrompter.m\
PXNearestNeighborScaleAlgorithm.m\
PXPalette.m\
PXPaletteSwitcher.m\
PXPencilTool.m\
PXPencilToolPropertiesView.m\
PXPixel.m\
PXPoint.m\
PXPreferencesController.m\
PXPreviewController.m\
PXPreviewResizeSizeView.m\
PXRectangleTool.m\
PXRectangleToolPropertiesView.m\
PXRectangularSelectionTool.m\
PXScale2xScaleAlgorithm.m\
PXScaleAlgorithm.m\
PXScaleController.m\
PXSelectionLayer.m\
PXSlashyBackground.m\
PXTool.m\
PXToolMatrix.m\
PXToolPaletteController.m\
PXToolPropertiesController.m\
PXToolPropertiesView.m\
PXToolSwitcher.m\
PXWelcomeController.m\
PXZoomTool.m\
SBCenteringClipView.m\
SubviewTableViewCell.m\
SubviewTableViewController.m\
UKFeedbackProvider.m\
UKPrefsPanel.m\
UKUpdateChecker.m\
PXPanelManager.m\
PXUserWarmer.m\
main.m

#PXBitmapExporter.m\
#PXPSDHandler.m\
#PXGifExporter.m\


Pixen_LANGUAGES = English
Pixen_RESOURCE_FILES  = *.png *.tiff *.pxi

Pixen_LOCALIZED_RESOURCE_FILES  = MainMenu.gorm\
PXDocument.gorm\
PXAbout.gorm\
PXBackgroundController.gorm\
PXColorPalette.gorm\
PXDiscoverPixen.gorm\
PXGradientBuilder.gorm\
PXGridSettingsPrompter.gorm\
PXImageSizePrompt.gorm\
PXInfoPanel.gorm\
PXLayerController.gorm\
PXNamePrompt.gorm\
PXPreview.gorm\
PXPreferences.gorm\
PXToolPalette.gorm\
PXMonotoneBackgroundConfigurator.gorm\
PXPencilToolPropertiesView.gorm \
PXRectangleToolPropertiesView.gorm \
PXEllipseToolPropertiesView.gorm \
PXBlankPropertiesView.gorm \
PXDuotoneBackgroundConfigurator.gorm \
PXImageBackgroundConfigurator.gorm \
PXToolProperties.gorm\
PXLayerDetailsView.gorm\
Localizable.strings\
Credits.html

Pixen_OBJCFLAGS += -Wno-import
#Pixen_OBJCFLAGS += -Wall 

include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make

