#import <string.h>
#import <objc/List.h>
#import <objc/Storage.h>

#import <AppKit/NSColor.h>
#import <AppKit/NSGraphics.h>
#import <AppKit/NSApplication.h>
#import <AppKit/NSColorPanel.h>
#import <AppKit/NSColorWell.h>
#import <AppKit/NSDataLink.h>
#import <AppKit/NSFont.h>
#import <AppKit/NSMatrix.h>
#import <AppKit/NSPageLayout.h>
#import <AppKit/NSPopUpButton.h>
#import <AppKit/NSPanel.h>
#import <AppKit/NSPrintInfo.h>
#import <AppKit/NSSavePanel.h>
#import <AppKit/NSSlider.h>
#import <AppKit/NSText.h>
#import <AppKit/NSTextView.h>
#import <AppKit/NSTextField.h>
#import <AppKit/obsoleteGraphics.h>

#import "../undo.subproj/Change.h"
#import "../undo.subproj/ChangeManager.h"

#import "../propertyList.h"
#import "../Graphic.h"
#import "../GraphicView.h"
#import "../Group.h"
#import "../Inspector.h"
#import "../TextGraphic.h"
#import "../GridView.h"
#import "../DrawSpellText.h"
#import "../DrawDocument.h"
#import "../DrawPageLayout.h"
#import "../DrawApp.h"

#import "ChangeDetail.h"
#import "EndEditingGraphicsChange.h"
#import "GraphicsChange.h"
#import "DeleteGraphicsChange.h"
#import "CutGraphicsChange.h"
#import "GridChange.h"
#import "GroupGraphicsChange.h"
#import "LockGraphicsChange.h"
#import "PasteGraphicsChange.h"
#import "PerformTextGraphicsChange.h"
#import "ReorderGraphicsChange.h"
#import "BringToFrontGraphicsChange.h"
#import "ResizeGraphicsChange.h"
#import "SendToBackGraphicsChange.h"
#import "SimpleGraphicsChange.h"
#import "AlignGraphicsChange.h"
#import "ArrowGraphicsChange.h"
#import "AspectRatioGraphicsChange.h"
#import "DimensionsGraphicsChange.h"
#import "FillGraphicsChange.h"
#import "LineCapGraphicsChange.h"
#import "LineColorGraphicsChange.h"
#import "LineJoinGraphicsChange.h"
#import "LineWidthGraphicsChange.h"
#import "MoveGraphicsChange.h"
#import "StartEditingGraphicsChange.h"
#import "CreateGraphicsChange.h"
#import "UngroupGraphicsChange.h"
#import "UnlockGraphicsChange.h"
#import "LocalizableStringsForGraphicsUndo.h"
