include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=pao2png 

pao2png_C_FILES= convert.c pao2png.c paoread.c

pao2png_HEADER_FILES= pao2png.h 


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble







