include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=newicon 

newicon_C_FILES=custom.c dirmark.c event.c newicon.c pnmread.c utils.c

newicon_HEADER_FILES=custom.h dirmark.h  event.h pnmread.h utils.h


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble





