include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=xbm2pbm 

xbm2pbm_C_FILES= xbm2pbm.c 

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
