include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=ras2ppm 

ras2ppm_C_FILES=ras2ppm.c ras2pxo.c rasio.c

ras2ppm_HEADER_FILES=ras2pxo.h rasterfile.h ras2ppm.h


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble



