include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=Posterize
BUNDLE_NAME= Posterize
BUNDLE_EXTENSION=.bundle

Posterize_OBJC_FILES= PosterCtrl.m  Posterizer.m

Posterize_RESOURCE_FILES=Posterize.gorm


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
