// _PXImageSizePrompt_EOArchive_English.java
// Generated by EnterpriseObjects palette at Wednesday, June 2, 2004 10.51.30 US/Central

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _PXImageSizePrompt_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOForm _nsForm0;
    com.webobjects.eointerface.swing.EOFormCell _eoFormCell0, _eoFormCell1;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0;
    com.webobjects.foundation.NSNumberFormatter _nsNumberFormatter0, _nsNumberFormatter1;
    javax.swing.JButton _nsButton0;
    javax.swing.JPanel _nsView0;

    public _PXImageSizePrompt_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsNumberFormatter1 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _nsNumberFormatter0 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Use this Size"), "NSButton");
        _eoFormCell1 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "NSFormCell1");
        _eoFormCell0 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "NSFormCell");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "sizeForm")) != null)) {
            _nsForm0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOForm)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsForm0");
        } else {
            _nsForm0 = (com.webobjects.eointerface.swing.EOForm)_registered(new com.webobjects.eointerface.swing.EOForm(2, 1, 1, 8), "NSForm1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "useEnteredSize", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_nsForm0") == null) {
            _connect(_owner(), _nsForm0, "sizeForm");
        }
    }

    protected void _init() {
        super._init();
        _nsNumberFormatter1.setMinimum(new java.math.BigDecimal("1"));
        _nsNumberFormatter0.setMinimum(new java.math.BigDecimal("1"));
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Please specify the size of the image.");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_eoFormCell1, "Lucida Grande", 13, Font.PLAIN);
        _eoFormCell1.setTitle("Height:");
        _eoFormCell1.setTitleWidth(55);
        _eoFormCell1.fieldComponent().setPreferredSize(new Dimension(2, 22));
        _eoFormCell1.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _setFontForComponent(_eoFormCell0, "Lucida Grande", 13, Font.PLAIN);
        _eoFormCell0.setTitle("Width:");
        _eoFormCell0.setTitleWidth(55);
        _eoFormCell0.fieldComponent().setPreferredSize(new Dimension(2, 22));
        _eoFormCell0.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        if (_replacedObjects.objectForKey("_nsForm0") == null) {
            _eoFormCell0.setSize(1, 2147483647);
            _eoFormCell0.setLocation(14, 2147483647);
            _nsForm0.add(_eoFormCell0);
            _eoFormCell1.setSize(1, 2147483647);
            _eoFormCell1.setLocation(14, 2147483647);
            _nsForm0.add(_eoFormCell1);
            _setFontForComponent(_nsForm0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsForm0.setSize(106, 52);
        _nsForm0.setLocation(13, 45);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsForm0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsForm0);
        _nsTextField0.setSize(233, 17);
        _nsTextField0.setLocation(11, 20);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsButton0.setSize(113, 26);
        _nsButton0.setLocation(131, 75);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(253, 111);
            _eoFrame0.setTitle("Specify Size");
            _eoFrame0.setLocation(212, 464);
            _eoFrame0.setSize(253, 111);
        }
    }
}
