include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=Resize
BUNDLE_NAME= Resize
BUNDLE_EXTENSION=.bundle

Resize_OBJC_FILES=DCTscaler.m ImageResize.m Thumbnailer.m resize.m

Resize_HEADER_FILES=DCTscaler.h ImageResize.h Thumbnailer.h resize.h 

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
