include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME=BackgCtr
BUNDLE_NAME= BackgCtr
BUNDLE_EXTENSION=.bundle

BackgCtr_OBJC_FILES=BackgCtr.m Background.m FullScreenView.m FullScreenWindow.m \


BackgCtr_HEADER_FILES= ADSlave.h

BackgCtr_RESOURCE_FILES=BackgCtr.h backgops.h Background.h FullScreenView.h \
FullScreenWindow.h CRightArrow.tiff CLeftArrow.tiff CPause.tiff


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/bundle.make
-include GNUmakefile.postamble
